trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  tag: '$(Build.BuildId)'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      name: Default
    steps:
    - task: Docker@2
      displayName: 'Build and push the image to container registry'
      inputs:
          command: buildAndPush
          buildContext: $(Build.Repository.LocalPath)
          repository: $(webRepository)
          dockerfile: 'C:/agent/_work/1/s/Korolenko/Dockerfile'
          containerRegistry: 'Container Korolenko'
          tags: |
            $(tag)

- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      name: Default
    variables:
    - group: Release
    steps:
    - task: AzureWebAppContainer@1
      inputs:
       appName: $(WebAppName)
       azureSubscription: 'Resource Manager Korolenko'
       imageName: $(RegistryName)/$(webRepository):$(build.buildId)
